server:
  port: 5000

external-api:
  base-url: ${EXTERNAL_API_BASE_URL:http://localhost:3001}
  connect-timeout: ${EXTERNAL_API_CONNECT_TIMEOUT:1s}
  response-timeout: ${EXTERNAL_API_RESPONSE_TIMEOUT:8s}

similar-products:
  max-concurrency: ${SIMILAR_PRODUCTS_MAX_CONCURRENCY:8}

cache:
  products:
    maximum-size: ${PRODUCT_CACHE_MAXIMUM_SIZE:1000}
    ttl: ${PRODUCT_CACHE_TTL:5m}

logging:
  level:
    com.inditex.similarproducts: INFO
    reactor.netty.http.client: ERROR
